<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SolidarityGrid.Application\SolidarityGrid.Application.csproj" />
    <ProjectReference Include="..\SolidarityGrid.Contracts\SolidarityGrid.Contracts.csproj" />
    <ProjectReference Include="..\SolidarityGrid.Infrastructure\SolidarityGrid.Infrastructure.csproj" />
  </ItemGroup>
</Project>
