<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SolidarityGrid.Application\SolidarityGrid.Application.csproj" />
    <ProjectReference Include="..\SolidarityGrid.Contracts\SolidarityGrid.Contracts.csproj" />
    <ProjectReference Include="..\SolidarityGrid.Domain\SolidarityGrid.Domain.csproj" />
  </ItemGroup>
</Project>
