// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolidarityGrid.Infrastructure.Persistence;

#nullable disable

namespace SolidarityGrid.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SolidarityGridDbContext))]
    [Migration("20260723205054_InitialNodePaymentStorage")]
    partial class InitialNodePaymentStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("SolidarityGrid.Domain.Payments.Payment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key")
                        .UseCollation("BINARY");

                    b.Property<long?>("LeaseExpiresAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("OwnerNodeId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_node_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("Term")
                        .HasColumnType("INTEGER")
                        .HasColumnName("term");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_payments_idempotency_key");

                    b.HasIndex("LeaseExpiresAtUtc")
                        .HasDatabaseName("IX_payments_lease_expires_at_utc");

                    b.HasIndex("OwnerNodeId")
                        .HasDatabaseName("IX_payments_owner_node_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_payments_status");

                    b.HasIndex("Status", "LeaseExpiresAtUtc")
                        .HasDatabaseName("IX_payments_status_lease_expires_at_utc");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_payments_amount", "length(amount) > 0");

                            t.HasCheckConstraint("CK_payments_attempt", "attempt >= 0");

                            t.HasCheckConstraint("CK_payments_currency", "length(currency) = 3");

                            t.HasCheckConstraint("CK_payments_term", "term >= 0");

                            t.HasCheckConstraint("CK_payments_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("SolidarityGrid.Domain.Payments.Payment", b =>
                {
                    b.OwnsOne("SolidarityGrid.Domain.Payments.Money", "Amount", b1 =>
                        {
                            b1.Property<string>("PaymentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("currency");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
